"""
mentorml.reporting.html_report
--------------------------------
Phase 8: Interactive HTML Report Generator

Generates self-contained, single-file HTML reports with embedded Plotly
charts.  The report requires no server — a stakeholder can open it in any
modern browser and interact with charts.

Requirements
------------
``pip install mentorml[report]`` (plotly + jinja2)

Graceful degradation
--------------------
If plotly or jinja2 is not installed, the generator falls back to a simple
HTML report without interactive charts.
"""

from __future__ import annotations

import json
import logging
import os
from datetime import datetime, timezone
from typing import Any

from mentorml.core.decision import DecisionLog, Severity

logger = logging.getLogger(__name__)

try:
    import plotly.graph_objects as go  # type: ignore[import-untyped]

    _PLOTLY_AVAILABLE = True
except ImportError:  # pragma: no cover
    _PLOTLY_AVAILABLE = False

try:
    from jinja2 import Environment, BaseLoader  # type: ignore[import-untyped]

    _JINJA2_AVAILABLE = True
except ImportError:  # pragma: no cover
    _JINJA2_AVAILABLE = False


# ---------------------------------------------------------------------------
# HTML Template
# ---------------------------------------------------------------------------

_HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{{ title }}</title>
  <style>
    :root {
      --bg: #0f1117; --surface: #1a1d2e; --accent: #7c3aed;
      --text: #e2e8f0; --muted: #94a3b8; --border: #2d3748;
      --success: #10b981; --warning: #f59e0b; --danger: #ef4444;
    }
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body { background: var(--bg); color: var(--text); font-family: 'Segoe UI', system-ui, sans-serif; line-height: 1.6; }
    .container { max-width: 1100px; margin: 0 auto; padding: 2rem; }
    header { background: linear-gradient(135deg, var(--accent) 0%, #1e1b4b 100%);
             padding: 2.5rem; border-radius: 12px; margin-bottom: 2rem; text-align: center; }
    header h1 { font-size: 2rem; margin-bottom: 0.5rem; }
    header p { color: var(--muted); }
    .card { background: var(--surface); border: 1px solid var(--border); border-radius: 10px; padding: 1.5rem; margin-bottom: 1.5rem; }
    .card h2 { color: var(--accent); margin-bottom: 1rem; font-size: 1.2rem; border-bottom: 1px solid var(--border); padding-bottom: 0.5rem; }
    .stats-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(140px, 1fr)); gap: 1rem; margin-bottom: 1.5rem; }
    .stat { background: var(--surface); border: 1px solid var(--border); border-radius: 8px; padding: 1rem; text-align: center; }
    .stat .value { font-size: 1.8rem; font-weight: 700; color: var(--accent); }
    .stat .label { font-size: 0.8rem; color: var(--muted); text-transform: uppercase; letter-spacing: 0.05em; }
    table { width: 100%; border-collapse: collapse; font-size: 0.9rem; }
    th { background: var(--accent); color: white; padding: 0.75rem; text-align: left; }
    td { padding: 0.6rem 0.75rem; border-bottom: 1px solid var(--border); }
    tr:hover td { background: rgba(124,58,237,0.1); }
    .badge { display: inline-block; padding: 0.2rem 0.6rem; border-radius: 9999px; font-size: 0.75rem; font-weight: 600; }
    .badge-critical { background: rgba(239,68,68,0.2); color: #ef4444; }
    .badge-warning  { background: rgba(245,158,11,0.2); color: #f59e0b; }
    .badge-info     { background: rgba(99,102,241,0.2); color: #818cf8; }
    .badge-ok       { background: rgba(16,185,129,0.2); color: #10b981; }
    .chart-container { border-radius: 8px; overflow: hidden; margin: 1rem 0; }
    .narrative { white-space: pre-wrap; font-family: monospace; font-size: 0.85rem; background: #0a0c16;
                 border: 1px solid var(--border); border-radius: 8px; padding: 1rem; max-height: 500px; overflow-y: auto; }
    footer { text-align: center; color: var(--muted); font-size: 0.8rem; margin-top: 3rem; padding: 1rem; }
  </style>
</head>
<body>
<div class="container">
  <header>
    <h1>📊 {{ title }}</h1>
    <p>Generated by <strong>mentorml</strong> · {{ generated_at }}</p>
  </header>

  <!-- Stats Grid -->
  <div class="stats-grid">
    <div class="stat"><div class="value">{{ n_rows }}</div><div class="label">Rows</div></div>
    <div class="stat"><div class="value">{{ n_cols }}</div><div class="label">Columns</div></div>
    <div class="stat"><div class="value">{{ n_issues }}</div><div class="label">Quality Issues</div></div>
    <div class="stat"><div class="value">{{ n_decisions }}</div><div class="label">Decisions Made</div></div>
    {% if best_model %}
    <div class="stat"><div class="value" style="font-size:1rem">{{ best_model }}</div><div class="label">Best Model</div></div>
    {% endif %}
  </div>

  <!-- Data Quality -->
  <div class="card">
    <h2>🔍 Data Quality</h2>
    <p>Overall severity: <span class="badge badge-{{ overall_severity }}">{{ overall_severity | upper }}</span></p>
    {% if issues %}
    <br>
    <table>
      <thead><tr><th>Column</th><th>Issue</th><th>Severity</th><th>Metric</th></tr></thead>
      <tbody>
        {% for issue in issues %}
        <tr>
          <td>{{ issue.column or "dataset" }}</td>
          <td>{{ issue.detail }}</td>
          <td><span class="badge badge-{{ issue.severity }}">{{ issue.severity }}</span></td>
          <td>{{ "%.2f%%" | format(issue.metric * 100) if issue.metric else "—" }}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
    {% else %}
    <p style="color: var(--success)">✅ No significant quality issues found.</p>
    {% endif %}
  </div>

  <!-- Feature Importance Chart -->
  {% if feature_chart %}
  <div class="card">
    <h2>🏆 Top Feature Importances</h2>
    <div class="chart-container">{{ feature_chart }}</div>
  </div>
  {% endif %}

  <!-- Model Scores Chart -->
  {% if model_chart %}
  <div class="card">
    <h2>🤖 Model Comparison</h2>
    <div class="chart-container">{{ model_chart }}</div>
  </div>
  {% endif %}

  <!-- Narrative -->
  {% if narrative %}
  <div class="card">
    <h2>📝 Analysis Narrative</h2>
    <div class="narrative">{{ narrative }}</div>
  </div>
  {% endif %}

  <!-- Decision Log -->
  <div class="card">
    <h2>🗂️ Decision Log</h2>
    <table>
      <thead><tr><th>Component</th><th>Action</th><th>Severity</th><th>Rationale</th></tr></thead>
      <tbody>
        {% for rec in decisions %}
        <tr>
          <td>{{ rec.component }}</td>
          <td>{{ rec.action }}</td>
          <td><span class="badge badge-{{ rec.severity }}">{{ rec.severity }}</span></td>
          <td>{{ rec.rationale[:120] }}{% if rec.rationale|length > 120 %}…{% endif %}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>

  <footer>mentorml v0.1.0 · AI Data Scientist Copilot · Report generated {{ generated_at }}</footer>
</div>
</body>
</html>"""


class HTMLReportGenerator:
    """
    Phase 8: Self-contained HTML report generator.

    Produces a single ``.html`` file with embedded Plotly charts, a data
    quality table, the business narrative, and the full decision log.

    Falls back to plain HTML if plotly/jinja2 are not installed.

    Parameters
    ----------
    project_name : str
        Project name used in the report title and filename.

    Examples
    --------
    ::

        gen = HTMLReportGenerator(project_name="Churn Model")
        path = gen.generate(log, analysis_result, "reports/")
        print(f"Report written to {path}")
    """

    def __init__(self, project_name: str = "ML Project") -> None:
        self.project_name = project_name

    def generate(
        self,
        log: DecisionLog,
        output_dir: str = ".",
        analysis_result: dict[str, Any] | None = None,
        quality_report: dict[str, Any] | None = None,
        explanation_result: dict[str, Any] | None = None,
        model_selection_result: dict[str, Any] | None = None,
        narrative: str = "",
    ) -> str:
        """
        Render and write the HTML report.

        Parameters
        ----------
        log : DecisionLog
            The full decision log.
        output_dir : str
            Directory to write the report into.
        analysis_result : dict | None
            Phase 1 analysis output.
        quality_report : dict | None
            Phase 2 quality output.
        explanation_result : dict | None
            Phase 6 explanation output.
        model_selection_result : dict | None
            Phase 5 model selection output.
        narrative : str
            Phase 7 narrative string.

        Returns
        -------
        str
            Absolute path to the generated HTML file.
        """
        os.makedirs(output_dir, exist_ok=True)
        timestamp = datetime.now(tz=timezone.utc).strftime("%Y%m%d_%H%M%S")
        safe_name = self.project_name.lower().replace(" ", "_")
        filename = f"{safe_name}_{timestamp}.html"
        output_path = os.path.join(output_dir, filename)

        html = self._render(
            log,
            analysis_result,
            quality_report,
            explanation_result,
            model_selection_result,
            narrative,
        )

        with open(output_path, "w", encoding="utf-8") as fh:
            fh.write(html)

        logger.info("Report written to %s", output_path)
        return os.path.abspath(output_path)

    # ------------------------------------------------------------------
    # Private
    # ------------------------------------------------------------------

    def _render(
        self,
        log: DecisionLog,
        analysis_result: dict[str, Any] | None,
        quality_report: dict[str, Any] | None,
        explanation_result: dict[str, Any] | None,
        model_selection_result: dict[str, Any] | None,
        narrative: str,
    ) -> str:
        """Build the HTML string."""
        generated_at = datetime.now(tz=timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

        ctx: dict[str, Any] = {
            "title": self.project_name,
            "generated_at": generated_at,
            "n_rows": (analysis_result or {}).get("n_rows", "—"),
            "n_cols": (analysis_result or {}).get("n_cols", "—"),
            "n_issues": len((quality_report or {}).get("issues", [])),
            "n_decisions": len(log),
            "overall_severity": (quality_report or {}).get("overall_severity", "ok"),
            "issues": (quality_report or {}).get("issues", []),
            "best_model": (model_selection_result or {}).get("best_model_name", ""),
            "narrative": narrative,
            "decisions": list(log),
            "feature_chart": "",
            "model_chart": "",
        }

        if _PLOTLY_AVAILABLE:
            ctx["feature_chart"] = self._feature_chart(explanation_result)
            ctx["model_chart"] = self._model_chart(model_selection_result)

        if _JINJA2_AVAILABLE:
            env = Environment(loader=BaseLoader())
            template = env.from_string(_HTML_TEMPLATE)
            return template.render(**ctx)

        # Minimal fallback if jinja2 missing
        return self._minimal_html(ctx)

    @staticmethod
    def _feature_chart(explanation_result: dict[str, Any] | None) -> str:
        if not explanation_result or not _PLOTLY_AVAILABLE:
            return ""
        importances = explanation_result.get("feature_importances", [])[:15]
        if not importances:
            return ""
        features = [i["feature"] for i in reversed(importances)]
        values = [i["importance"] for i in reversed(importances)]
        fig = go.Figure(go.Bar(
            x=values, y=features, orientation="h",
            marker=dict(color=values, colorscale="Purples"),
        ))
        fig.update_layout(
            template="plotly_dark",
            paper_bgcolor="rgba(0,0,0,0)",
            plot_bgcolor="rgba(0,0,0,0)",
            margin=dict(l=10, r=10, t=10, b=10),
            height=400,
        )
        return fig.to_html(full_html=False, include_plotlyjs="cdn")

    @staticmethod
    def _model_chart(model_selection_result: dict[str, Any] | None) -> str:
        if not model_selection_result or not _PLOTLY_AVAILABLE:
            return ""
        scores = model_selection_result.get("cv_scores", {})
        if not scores:
            return ""
        best = model_selection_result.get("best_model_name", "")
        names = list(scores.keys())
        values = [scores[n] for n in names]
        colors = ["#7c3aed" if n == best else "#4b5563" for n in names]
        fig = go.Figure(go.Bar(
            x=names, y=values,
            marker_color=colors,
            text=[f"{v:.4f}" for v in values],
            textposition="auto",
        ))
        fig.update_layout(
            template="plotly_dark",
            paper_bgcolor="rgba(0,0,0,0)",
            plot_bgcolor="rgba(0,0,0,0)",
            margin=dict(l=10, r=10, t=10, b=10),
            height=350,
        )
        return fig.to_html(full_html=False, include_plotlyjs="cdn")

    @staticmethod
    def _minimal_html(ctx: dict[str, Any]) -> str:
        return (
            f"<html><head><title>{ctx['title']}</title></head>"
            f"<body><h1>{ctx['title']}</h1>"
            f"<p>Rows: {ctx['n_rows']}, Columns: {ctx['n_cols']}</p>"
            f"<p>Decisions: {ctx['n_decisions']}</p>"
            f"<pre>{ctx['narrative']}</pre>"
            f"</body></html>"
        )
